Repository TN4HPEL3/vinissimo, pull requests merged in 2024-06, with the labels that each got.

#61 Fix description
  src/pages/Wine/organisms/MenuWineBottlesTextOrganism/MenuWineBottlesTextOrganism.jsx
Labels: enhancement

#58 Fix reservation style
  src/components/templates/Reservation/ReservationTemplate.module.css
Labels: enhancement

#59 Fix link for opening in new window
  src/components/atoms/ContactLinkAtom/ContactLinkAtom.jsx
Labels: enhancement

#56 Fixed source in Map Atom
  src/components/atoms/Reservation/ReservationMapAtom/ReservationMapAtom.jsx
Labels: enhancement

#60 Deleted description, added price, added gap
  src/data/alcohols.json
  src/pages/Menu/organisms/MenuAlcoholsFirstPageOrganism/MenuAlcoholsFirstPageOrganism.jsx
  src/pages/Menu/templates/MenuPageAlcoholTemplate/MenuPageAlcoholTemplate.module.css
Labels: enhancement

#62 Fixed ref for avoiding error in console
  src/components/organisms/ArrowUpOrganism/ArrowUpOrganism.jsx
  src/components/templates/ArrowUpTemplate/ArrowUpTemplate.jsx
Labels: enhancement

#55 Add ".jsx" and ".js" extensions
  src/App.jsx
  src/components/atoms/CloseMobileMenuButtonAtom/CloseMobileMenuButtonAtom.jsx
  src/components/atoms/HeroAtom/HeroAtom.jsx
  src/components/atoms/NavigationListItemAtom/NavigationListItemAtom.jsx
  src/components/atoms/OpenMobileMenuButtonAtom/OpenMobileMenuButtonAtom.jsx
  src/components/molecules/ArrowUpMolecule/ArrowUpMolecule.jsx
  src/components/molecules/FooterIconsMolecule/FooterIconsMolecule.jsx
  src/components/molecules/FooterLinksMolecule/FooterLinksMolecule.jsx
  src/components/molecules/HashLinkMolecule/HashLinkMolecule.jsx
  src/components/molecules/NavigationListItemMolecule/NavigationListItemMolecule.jsx
  src/components/molecules/RateUsMolecule/RateUsMolecule.jsx
  src/components/molecules/ReservationMapMolecule/ReservationMapMolecule.jsx
  src/components/molecules/ReservationTextMolecule/ReservationTextMolecule.jsx
  src/components/organisms/ArrowUpOrganism/ArrowUpOrganism.jsx
  src/components/organisms/FooterOrganism/FooterOrganism.jsx
  src/components/organisms/HeroOrganism/HeroOrganism.jsx
  src/components/organisms/MenuButtonsOrganism/MenuButtonsOrganism.jsx
  src/components/organisms/MenuListOrganism/MenuListOrganism.jsx
  src/components/organisms/MobileMenuOrganism/MobileMenuOrganism.jsx
  src/components/organisms/RateUsOrganism/RateUsOrganism.jsx
  src/components/organisms/ReservationOrganism/ReservationOrganism.jsx
  src/components/templates/About/AboutTemplate.jsx
  src/components/templates/ArrowUpTemplate/ArrowUpTemplate.jsx
  src/components/templates/Footer/FooterTemplate.jsx
  src/components/templates/HeroTemplate/HeroTemplate.jsx
  src/components/templates/MobileMenuTemplate/MobileMenuTemplate.jsx
  src/components/templates/NavigationTemplate/NavigationTemplate.jsx
  src/components/templates/Reservation/ReservationTemplate.jsx
  src/pages/Home/HomePage.jsx
  src/pages/Menu/atoms/MenuPageLinkAtom.jsx
  src/pages/Menu/molecules/MenuPageArrowButtonMolecule/MenuPageArrowLeftButtonMolecule.jsx
  src/pages/Menu/molecules/MenuPageArrowButtonMolecule/MenuPageArrowRightButtonMolecule.jsx
  src/pages/Menu/molecules/MenuPageButtonsMolecule/MenuPageButtonMolecule.jsx
  src/pages/Menu/organisms/MenuAlcoholsFirstPageOrganism/MenuAlcoholsFirstPageOrganism.jsx
  src/pages/Menu/organisms/MenuAlcoholsOrganism/MenuAlcoholsOrganism.jsx
  src/pages/Menu/organisms/MenuAlcoholsSecondPageOrganism/MenuAlcoholsSecondPageOrganism.jsx
  src/pages/Menu/organisms/MenuPageButtonsOrganism/MenuPageButtonsOrganism.jsx
  src/pages/Menu/templates/MenuPageAlcoholTemplate/MenuPageAlcoholTemplate.jsx
  src/pages/Menu/templates/MenuPageFoodTemplate/MenuPageFoodTemplate.jsx
  src/pages/Wine/WinePage.jsx
  src/pages/Wine/organisms/MenuWineBottlesTextOrganism/MenuWineBottlesTextOrganism.jsx
  src/pages/Wine/organisms/WineBottlesPages/WineBottlesEighthPageOrganism.jsx
  src/pages/Wine/organisms/WineBottlesPages/WineBottlesEleventhPageOrganism.jsx
  src/pages/Wine/organisms/WineBottlesPages/WineBottlesFifthPageOrganism.jsx
  src/pages/Wine/organisms/WineBottlesPages/WineBottlesFirstPageOrganism.jsx
  src/pages/Wine/organisms/WineBottlesPages/WineBottlesFourthPageOrganism.jsx
  src/pages/Wine/organisms/WineBottlesPages/WineBottlesNinthPageOrganism.jsx
  src/pages/Wine/organisms/WineBottlesPages/WineBottlesSecondPageOrganism.jsx
  src/pages/Wine/organisms/WineBottlesPages/WineBottlesSeventhPageOrganism.jsx
  src/pages/Wine/organisms/WineBottlesPages/WineBottlesSixthPageOrganism.jsx
  src/pages/Wine/organisms/WineBottlesPages/WineBottlesTenthPageOrganism.jsx
  src/pages/Wine/organisms/WineBottlesPages/WineBottlesThirdPageOrganism.jsx
  src/pages/Wine/organisms/WineBottlesPages/WineBottlesTwelfthPageOrganism.jsx
  src/pages/Wine/organisms/WineGlassesFirstPageOrganism/WineGlassesFirstPageOrganism.jsx
  src/pages/Wine/organisms/WineGlassesSecondPageOrganism/WineGlassesSecondPageOrganism.jsx
  src/pages/Wine/organisms/WineGlassesThirdPageOrganism/WineGlassesThirdPageOrganism.jsx
  src/pages/Wine/organisms/WinePageButtonsOrganism/WinePageButtonsOrganism.jsx
  src/pages/Wine/organisms/WinePageListOrganism/WineGlassesListOrganism.jsx
  src/pages/Wine/templates/WineBottlesTemplate/WineBottlesTemplate.jsx
  src/pages/Wine/templates/WineGlassesTemplate/WineGlassesTemplate.jsx
Labels: enhancement

#57 Mobile menu bugfix
  src/components/atoms/HashLinkAtom/HashLinkAtom.jsx
  src/components/organisms/MobileMenuOrganism/MobileMenuOrganism.jsx
  src/pages/Home/HomePage.jsx
Labels: enhancement

#64 Add active route parameter, add className depending on active route location
  src/components/atoms/NavigationListItemAtom/NavigationListItemAtom.jsx
  src/components/molecules/NavigationListItemMolecule/NavigationListItemMolecule.jsx
  src/components/organisms/MobileMenuOrganism/MobileMenuOrganism.jsx
  src/components/organisms/NavigationListOrganisms/NavigationListOrganisms.jsx
Labels: enhancement

#63 Add without on true for avoiding error in console
  src/components/atoms/ContactLinkAtom/ContactLinkAtom.jsx
Labels: enhancement

#13 Implemented Page404 with content.
  src/App.jsx
  src/pages/Page404/Page404.jsx
  src/pages/Page404/Page404.module.css
  src/pages/Page404/atoms/Page404Atom.jsx
  src/pages/Page404/atoms/Page404ButtonAtom/Page404ButtonAtom.jsx
  src/pages/Page404/atoms/Page404ContentAtom/Page404ContentAtom.jsx
  src/pages/Page404/atoms/Page404ErrorAtom/Page404ErrorAtom.jsx
  src/pages/Page404/molecules/Page404ButtonMolecule/Page404ButtonMolecule.jsx
  src/pages/Page404/molecules/Page404Molecule/Page404Molecule.jsx
  src/pages/Page404/molecules/Page404Molecule/Page404Molecule.module.css
  src/pages/Page404/organisms/Page404Organism/Page404Organism.jsx
  src/pages/Page404/organisms/Page404Organism/Page404Organism.module.css
  src/pages/Page404/template/Page404Template.jsx
  src/pages/Page404/template/Page404Template.module.css
Labels: enhancement

#65 Add underline on hover to "reservation" in navigation
  src/components/atoms/HashLinkAtom/HashLinkAtom.jsx
Labels: enhancement

#67 Added transition on hover
  src/pages/Wine/molecules/WinePageCategoriesButtonsMolecule/WinePageCategoriesButtonsMolecule.module.css
Labels: enhancement

#71 Added privacy policy to footer
  public/privacyPolicy.pdf
  src/components/atoms/FooterDownloadLinkAtom/FooterDownloadLinkAtom.jsx
  src/components/molecules/FooterLinksMolecule/FooterLinksMolecule.jsx
  src/components/organisms/FooterOrganism/FooterOrganism.jsx
Labels: enhancement

#72 Go to the top of the page when 'Home' or the logo is clicked
  src/components/atoms/NavigationListItemAtom/NavigationListItemAtom.jsx
  src/components/molecules/NavigationLogoMolecule/NavigationLogoMolecule.jsx
Labels: enhancement

#70 Fux structure so link is opening on first click
  src/components/organisms/ReservationOrganism/ReservationOrganism.jsx
Labels: enhancement

#69 Made one transition for all elements
  src/components/atoms/NavigationListItemAtom/NavigationListItemAtom.module.css
  src/components/atoms/buttonAtom/ButtonAtom.module.css
  src/components/molecules/ArrowUpMolecule/ArrowUpMolecule.module.css
  src/components/molecules/FooterIconsMolecule/FooterIconsMolecule.module.css
  src/components/molecules/RateUsMolecule/RateUsMolecule.module.css
  src/components/organisms/FooterOrganism/FooterOrganism.module.css
  src/components/templates/MobileMenuTemplate/MobileMenuTemplate.module.css
  src/pages/Menu/molecules/MenuPageArrowButtonMolecule/MenuPageArrowButtonMolecule.module.css
  src/pages/Menu/templates/MenuPageAlcoholTemplate/MenuPageAlcoholTemplate.module.css
  src/pages/Wine/molecules/WinePageCategoriesButtonsMolecule/WinePageCategoriesButtonsMolecule.module.css
  src/style/variables.css
Labels: enhancement

#68 Added a function for changing pages when the arrow buttons "on keyboard" are clicked.
  package-lock.json
  package.json
  src/helpers/checkArrowDownButton.js
  src/pages/Menu/templates/MenuPageAlcoholTemplate/MenuPageAlcoholTemplate.jsx
  src/pages/Wine/molecules/WinePageCategoriesButtonsMolecule/WinePageCategoriesButtonsMolecule.jsx
  src/pages/Wine/molecules/WinePageCategoriesButtonsMolecule/WinePageCategoriesButtonsMolecule.module.css
  src/pages/Wine/templates/WineBottlesTemplate/WineBottlesTemplate.jsx
  src/pages/Wine/templates/WineGlassesTemplate/WineGlassesTemplate.jsx
Labels: enhancement

#66 Added buttons for downloading menu with wines
  public/WinesBottles.pdf
  public/WinesGlasses.pdf
  src/pages/Wine/atoms/DownloadMenuAtom.jsx
  src/pages/Wine/atoms/DownloadMenuAtom.module.css
  src/pages/Wine/templates/WineBottlesTemplate/WineBottlesTemplate.jsx
  src/pages/Wine/templates/WineGlassesTemplate/WineGlassesTemplate.jsx
Labels: enhancement

#73 Add text to reservation section
  src/components/atoms/Reservation/ReservationTextAtom/ReservationTextAtom.jsx
  src/components/atoms/Reservation/ReservationTextAtom/ReservationTextAtom.module.css
Labels: enhancement

#74 Created Events Page
  public/images/VIP.jpeg
  public/images/sala.jpeg
  src/App.jsx
  src/pages/Events/EventsPage.jsx
  src/pages/Events/atoms/EventsContactAtom/EventsContactAtom.jsx
  src/pages/Events/atoms/EventsContactAtom/EventsContactAtom.module.css
  src/pages/Events/atoms/EventsDescriptionAtom/EventsDescriptionAtom.jsx
  src/pages/Events/molecules/EventsContactMolecule/EventsContactMolecule.jsx
  src/pages/Events/molecules/EventsDescriptionMolecule/EventsDescriptionMolecule.jsx
  src/pages/Events/molecules/EventsImagesMolecule/EventsImagesMolecule.jsx
  src/pages/Events/molecules/EventsImagesMolecule/EventsImagesMolecule.module.css
  src/pages/Events/organisms/EventsOrganism.jsx
  src/pages/Events/templates/EventsTemplate.jsx
  src/pages/Events/templates/EventsTemplate.module.css
Labels: enhancement

#75 Created Team Page
  src/App.jsx
  src/pages/Team/TeamPage.jsx
  src/pages/Team/atoms/TeamPageNameAtom/TeamPageNameAtom.jsx
  src/pages/Team/atoms/TeamPageNameAtom/TeamPageNameAtom.module.css
  src/pages/Team/atoms/TeamPageTitleAtom/TeamPageTitleAtom.jsx
  src/pages/Team/atoms/TeamPageTitleAtom/TeamPageTitleAtom.module.css
  src/pages/Team/molecules/TeamPageMolecule.jsx
  src/pages/Team/molecules/TeamPageMolecule.module.css
  src/pages/Team/organisms/TeamPageOrganism.jsx
  src/pages/Team/organisms/TeamPageOrganism.module.css
  src/pages/Team/templates/TeamPageTemplate.jsx
Labels: enhancement

#77 Fix calling function smoothScroll and hiding ArrowUp
  src/components/templates/HeroTemplate/HeroTemplate.jsx
  src/pages/Home/HomePage.jsx
  src/pages/Menu/MenuPage.jsx
  src/pages/Wine/WinePage.jsx
Labels: enhancement

#76 Updated menu with food
  src/components/templates/Menu/MenuTemplate.jsx
  src/data/menu.json
Labels: enhancement

#79 Blocked scroll when mobile menu is open
  src/components/templates/MobileMenuTemplate/MobileMenuTemplate.jsx
  src/components/templates/MobileMenuTemplate/MobileMenuTemplate.module.css
Labels: enhancement

#80 Fix description
  src/pages/Team/molecules/TeamPageMolecule.jsx
Labels: enhancement

#81 Fix margin
  src/pages/Events/templates/EventsTemplate.module.css
Labels: enhancement

#82 Fix mistakes
  src/components/templates/MobileMenuTemplate/MobileMenuTemplate.jsx
  src/components/templates/MobileMenuTemplate/MobileMenuTemplate.module.css
  src/pages/Events/templates/EventsTemplate.module.css
  src/pages/Team/molecules/TeamPageMolecule.jsx
Labels: enhancement

#84 Add smooth scroll to top fn when clicking on menu page link
  src/pages/Menu/atoms/MenuPageLinkAtom.jsx
Labels: bug

#85 Merge some bug fixes into main
  src/components/templates/Footer/FooterTemplate.module.css
  src/components/templates/HeroTemplate/HeroTemplate.module.css
  src/components/templates/Section/SectionTemplate.module.css
  src/index.css
  src/pages/Menu/atoms/MenuPageLinkAtom.jsx
Labels: bug

#86 Test page comment
  src/pages/TestPage/TestPage.jsx
Labels: bug

#87 Dev
  src/pages/TestPage/TestPage.jsx
Labels: bug, enhancement

#88 Fixed MobileMenuTemplate to prevent horizontal scroll
  src/components/templates/MobileMenuTemplate/MobileMenuTemplate.jsx
Labels: bug

#89 Delete unused import
  src/components/templates/MobileMenuTemplate/MobileMenuTemplate.jsx
Labels: bug

#90 Merge DEV to fix appearing horizontal scroll
  src/components/templates/MobileMenuTemplate/MobileMenuTemplate.jsx
Labels: bug
